# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1065, 950)
        self.input_scale = QtWidgets.QLineEdit(Form)
        self.input_scale.setGeometry(QtCore.QRect(780, 250, 131, 41))
        self.input_scale.setObjectName("input_scale")
        self.btn_start = QtWidgets.QPushButton(Form)
        self.btn_start.setGeometry(QtCore.QRect(50, 60, 71, 51))
        self.btn_start.setObjectName("btn_start")
        self.btn_pause = QtWidgets.QPushButton(Form)
        self.btn_pause.setGeometry(QtCore.QRect(270, 60, 81, 61))
        self.btn_pause.setObjectName("btn_pause")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(680, 250, 54, 31))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(680, 200, 91, 31))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 240, 54, 31))
        self.label.setObjectName("label")
        self.btn_sample_time = QtWidgets.QPushButton(Form)
        self.btn_sample_time.setGeometry(QtCore.QRect(460, 250, 121, 31))
        self.btn_sample_time.setObjectName("btn_sample_time")
        self.format_list = QtWidgets.QComboBox(Form)
        self.format_list.setGeometry(QtCore.QRect(137, 191, 191, 27))
        self.format_list.setObjectName("format_list")
        self.format_list.addItem("")
        self.format_list.addItem("")
        self.btn_tilt_flip = QtWidgets.QPushButton(Form)
        self.btn_tilt_flip.setGeometry(QtCore.QRect(920, 120, 101, 61))
        self.btn_tilt_flip.setObjectName("btn_tilt_flip")
        self.btn_rotate = QtWidgets.QPushButton(Form)
        self.btn_rotate.setGeometry(QtCore.QRect(940, 210, 91, 71))
        self.btn_rotate.setObjectName("btn_rotate")
        self.input_degree = QtWidgets.QLineEdit(Form)
        self.input_degree.setGeometry(QtCore.QRect(780, 200, 131, 41))
        self.input_degree.setObjectName("input_degree")
        self.pic1 = QtWidgets.QLabel(Form)
        self.pic1.setGeometry(QtCore.QRect(70, 320, 891, 531))
        self.pic1.setScaledContents(False)
        self.pic1.setObjectName("pic1")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 190, 91, 31))
        self.label_2.setObjectName("label_2")
        self.camera_parameter = QtWidgets.QComboBox(Form)
        self.camera_parameter.setGeometry(QtCore.QRect(140, 240, 191, 27))
        self.camera_parameter.setObjectName("camera_parameter")
        self.camera_parameter.addItem("")
        self.information_output = QtWidgets.QTextEdit(Form)
        self.information_output.setGeometry(QtCore.QRect(430, 40, 201, 121))
        self.information_output.setObjectName("information_output")
        self.btn_close = QtWidgets.QPushButton(Form)
        self.btn_close.setGeometry(QtCore.QRect(150, 60, 81, 51))
        self.btn_close.setObjectName("btn_close")
        self.btn_pan_flip = QtWidgets.QPushButton(Form)
        self.btn_pan_flip.setGeometry(QtCore.QRect(920, 30, 101, 61))
        self.btn_pan_flip.setObjectName("btn_pan_flip")
        self.input_sample_time = QtWidgets.QLineEdit(Form)
        self.input_sample_time.setGeometry(QtCore.QRect(460, 200, 131, 41))
        self.input_sample_time.setObjectName("input_sample_time")
        self.btn_information_inquire = QtWidgets.QPushButton(Form)
        self.btn_information_inquire.setGeometry(QtCore.QRect(700, 70, 101, 61))
        self.btn_information_inquire.setObjectName("btn_information_inquire")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_start.setText(_translate("Form", "启动"))
        self.btn_pause.setText(_translate("Form", "暂停"))
        self.label_4.setText(_translate("Form", "缩放比例"))
        self.label_3.setText(_translate("Form", "角度"))
        self.label.setText(_translate("Form", "宽*高*FPS"))
        self.btn_sample_time.setText(_translate("Form", "设置采样时间(ms)"))
        self.format_list.setItemText(0, _translate("Form", "YUY2"))
        self.format_list.setItemText(1, _translate("Form", "MJPG"))
        self.btn_tilt_flip.setText(_translate("Form", "垂直镜像"))
        self.btn_rotate.setText(_translate("Form", "旋转"))
        self.pic1.setText(_translate("Form", "相机1画面"))
        self.label_2.setText(_translate("Form", "传输格式"))
        self.camera_parameter.setItemText(0, _translate("Form", "当前为默认参数"))
        self.btn_close.setText(_translate("Form", "停止"))
        self.btn_pan_flip.setText(_translate("Form", "水平镜像"))
        self.btn_information_inquire.setText(_translate("Form", "信息查询"))

