# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 961)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_pause = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pause.setGeometry(QtCore.QRect(270, 60, 81, 61))
        self.btn_pause.setObjectName("btn_pause")
        self.pic1 = QtWidgets.QLabel(self.centralwidget)
        self.pic1.setGeometry(QtCore.QRect(70, 320, 891, 531))
        self.pic1.setScaledContents(False)
        self.pic1.setObjectName("pic1")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(50, 60, 71, 51))
        self.btn_start.setObjectName("btn_start")
        self.btn_sample_time = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sample_time.setGeometry(QtCore.QRect(460, 250, 121, 31))
        self.btn_sample_time.setObjectName("btn_sample_time")
        self.btn_pan_flip = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pan_flip.setGeometry(QtCore.QRect(730, 30, 101, 61))
        self.btn_pan_flip.setObjectName("btn_pan_flip")
        self.btn_rotate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rotate.setGeometry(QtCore.QRect(940, 210, 91, 71))
        self.btn_rotate.setObjectName("btn_rotate")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 240, 54, 31))
        self.label.setObjectName("label")
        self.input_degree = QtWidgets.QLineEdit(self.centralwidget)
        self.input_degree.setGeometry(QtCore.QRect(780, 200, 131, 41))
        self.input_degree.setObjectName("input_degree")
        self.btn_close = QtWidgets.QPushButton(self.centralwidget)
        self.btn_close.setGeometry(QtCore.QRect(150, 60, 81, 51))
        self.btn_close.setObjectName("btn_close")
        self.btn_tilt_flip = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tilt_flip.setGeometry(QtCore.QRect(730, 110, 101, 61))
        self.btn_tilt_flip.setObjectName("btn_tilt_flip")
        self.camera_parameter = QtWidgets.QComboBox(self.centralwidget)
        self.camera_parameter.setGeometry(QtCore.QRect(140, 240, 191, 27))
        self.camera_parameter.setObjectName("camera_parameter")
        self.camera_parameter.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(137, 191, 191, 27))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 190, 91, 31))
        self.label_2.setObjectName("label_2")
        self.information_output = QtWidgets.QTextEdit(self.centralwidget)
        self.information_output.setGeometry(QtCore.QRect(430, 40, 201, 121))
        self.information_output.setObjectName("information_output")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(680, 200, 91, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(680, 250, 54, 31))
        self.label_4.setObjectName("label_4")
        self.input_scale = QtWidgets.QLineEdit(self.centralwidget)
        self.input_scale.setGeometry(QtCore.QRect(780, 250, 131, 41))
        self.input_scale.setObjectName("input_scale")
        self.input_sample_time = QtWidgets.QLineEdit(self.centralwidget)
        self.input_sample_time.setGeometry(QtCore.QRect(460, 200, 131, 41))
        self.input_sample_time.setObjectName("input_sample_time")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1059, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_pause.setText(_translate("MainWindow", "暂停"))
        self.pic1.setText(_translate("MainWindow", "相机1画面"))
        self.btn_start.setText(_translate("MainWindow", "启动"))
        self.btn_sample_time.setText(_translate("MainWindow", "设置采样时间(ms)"))
        self.btn_pan_flip.setText(_translate("MainWindow", "水平镜像"))
        self.btn_rotate.setText(_translate("MainWindow", "旋转"))
        self.label.setText(_translate("MainWindow", "宽*高*FPS"))
        self.btn_close.setText(_translate("MainWindow", "停止"))
        self.btn_tilt_flip.setText(_translate("MainWindow", "垂直镜像"))
        self.camera_parameter.setItemText(0, _translate("MainWindow", "当前为默认参数"))
        self.label_2.setText(_translate("MainWindow", "传输格式"))
        self.label_3.setText(_translate("MainWindow", "角度"))
        self.label_4.setText(_translate("MainWindow", "缩放比例"))

